# Generated by Django 4.2.7 on 2023-12-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
